apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll
  template:
    metadata:
      labels:
        app: payroll
    spec:
      containers:
        - name: payroll-container
          image: 23mis0353/payroll-app